---
- hosts: all
  tasks:
  - name: install vim package
    ansible.builtin.yum:
      name: vim
      state: present
    when: ansible_distribution == "CentOS" and ansible_nodename == "mysql-machine-1.novalocal"
